sudo: required

language: generic


before_script:
  - npm install @angular/cli -g
  - npm install --unsafe-perm=true --allow-root
  - ng build 

deploy:
- provider: s3
  access_key_id: $my_id
  secret_access_key: $my_secret
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on:   
    branch: master
  bucket: nates3practice
  region: us-east-1
- provider: codedeploy
  access_key_id: $my_id
  secret_access_key: $my_secret
  bucket: nates3practice
  key: latest.zip
  bundle_type: zip
  application: weatherApp
  deployment_group: production
  region: us-east-1
  on:   
    branch: master 

script:
  - zip -r latest appspec.yml dist/out/.
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip


